### ISSUE TITLE
Женя как обычно

### ISSUE THREAD

**Issue by kurigohan0** [team-305/Practice-01.01#1]
Вот короче тупой комит. В этот раз просто предупреждение, а в следующий раз конвертируем в outside.

**Comment by spyinfo** [comment]
+

**Comment by kurigohan0** [comment]
> МОИ ЛУЧШИЕ ФАЙЛЫ
Так нельзя

**Comment by spyinfo** [comment]
`Так как кикнули этого аутсайдера, то решил закрыть Issue`
